organisation: "Association Maison Verte d'Haïti"
tagline: "Semer le vert, protéger la Terre, faire respirer Haïti"
logo: /assets/img/logomaisonverte.jpg
email: info@maisonvertehaiti.org
address: "P-A-P Haïti"
map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d121020.34891971707!2d-72.3668628472702!3d18.579181929868223!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8eb9dd57503eaa91%3A0x3cd5815df929aa08!2sPort-au-Prince!5e0!3m2!1sen!2sht!4v1767909895371!5m2!1sen!2sht"
facebook_url: "https://www.facebook.com/cinecolohaiti7"
twitter_url: ""
instagram_url: ""
linkedin_url: ""
newsletter_text: "Recevez des idées écoresponsables pour vivre plus sainement tout en respectant la nature."
footer_partner_text: "Projet réalisé en partenariat avec l'Ambassade de France"
footer_partner_url: "https://ht.ambafrance.org/"
credit_name: "CHARLDE WEDSER"
credit_url: "https://konbittech.org"
