backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Actualités"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "slides"
    label: "Slides"
    folder: "_slides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre du Slide", name: "title", widget: "string" }
      - { label: "Image du Slide", name: "image", widget: "image" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "presses"
    label: "Presse"
    folder: "_presses"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre de l'Article", name: "title", widget: "string" }
      - { label: "Source", name: "source", widget: "string" }
      - { label: "Lien de l'Article", name: "link", widget: "string" }
      - { label: "Date de Publication", name: "date", widget: "datetime" }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }
      - { label: "Contenu Complet", name: "body", widget: "markdown" }

  - name: "aboutus"
    label: "À Propos de Nous"
    folder: "_aboutus"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Mission", name: "mission", widget: "markdown" }
      - { label: "Valeurs", name: "mission", widget: "markdown" }
      - { label: "Histoire", name: "history", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }

  - name: "projets"
    label: "Projets"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre du Projet", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Lien du Projet", name: "project_link", widget: "string" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Images Gallery", name: "images_gallery", widget: "list", allow_add: true,
          field: { label: "Image", name: "image", widget: "image" }
        }
      - { label: "Videos", name: "videos", widget: "list", allow_add: true,
          field: { label: "Video URL", name: "video_url", widget: "string" }
        }

  - name: "coordonnateur"
    label: "Mot du Coordonnateur"
    folder: "_motducoordonateur"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Nom du Coordonnateur", name: "name", widget: "string" }
      - { label: "Message", name: "message", widget: "markdown" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }

  - name: "rapports"
    label: "Rapports Annuels"
    folder: "_rapportsannuels"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Année", name: "year", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Fichier PDF", name: "pdf_file", widget: "file" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }

  - name: "cours"
    label: "Cours et Ateliers"
    folder: "_coursesetateliers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre du Cours/Atelier", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Niveau du cours", name: "level", widget: "select", options: ["Débutant", "Intermédiaire", "Avancé"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Lien d'Inscription", name: "registration_link", widget: "string" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true } 
      - { label: "Videos", name: "videos", widget: "list", allow_add: true,
          field: { label: "Video URL", name: "video_url", widget: "string" }
        }

  - name: "contact"
    label: "Contact"
    folder: "_contact"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Message", name: "message", widget: "markdown" }

  - name: "faireundon"
    label: "Faire un Don"
    folder: "_faireundon"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Lien de Don", name: "lien", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bouton Texte", name: "button_text", widget: "string" }
      - { label: "Bouton Lien", name: "button_link", widget: "string" }

  - name: "partenaires"
    label: "Partenaires"
    folder: "_partenaires"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Nom du Partenaire", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Site Web", name: "website", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" } 
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }


  - name: "Bénévolat"
    label: "Bénévolat"
    folder: "_benevolat"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Lien d'Inscription", name: "registration_link", widget: "string" }
      - { label: "Ordre d'Affichage", name: "order", widget: "number" }
      - { label: "Actif", name: "active", widget: "boolean", default: true }  
