backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "public/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Actualites"
    name: "actualites"
    folder: "public/posts/actus"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Announcements"
    name: "announcements"
    folder: "public/posts/announcements"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Les Invites"
    name: "invites"
    folder: "public/posts/invites"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date Participation", name: "dateParticipation", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]      
  - label: "Editions"
    name: "editions"
    folder: "public/posts/editions"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Le Festival"
    name: "festival"
    folder: "public/posts/apropos"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]    
  - label: "La Boutique"
    name: "boutique"
    folder: "public/posts/boutique"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Films"
    name: "films"
    folder: "public/posts/films"
    create: true
    editor: "markdown"
    preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Settings"
    name: "settings"
    editor: "markdown"
    preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "public/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }

  - label: "Hero Slides"
    name: "Hero"
    editor:
    preview: false
    files:
      - label: "Hero"
        name: "items"
        file: "public/_data/hero.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: BTN, name: bouttonNavigation, widget: string }
              - { label: "Featured Image", name: "featuredImage", widget: "image" }
              - { label: URL, name: url, widget: string }
                         
      - label: "Quick Links"
        name: "links"
        file: "public/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      