backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "films"
    label: "Films"
    label_singular: "Film"
    folder: "data/films"
    extension: "json"
    format: "json"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "director", label: "Réalisateur", widget: "string" }
      - { name: "year", label: "Année", widget: "number" }
      - { name: "description", label: "Description", widget: "text" }

  - name: "invites"
    label: "Invités"
    folder: "data/invites"
    extension: "json"
    format: "json"
    create: true
    fields:
      - { name: "name", label: "Nom", widget: "string" }
      - { name: "bio", label: "Biographie", widget: "text" }
      - { name: "image", label: "Photo", widget: "image" }

  - name: "events"
    label: "Événements"
    folder: "data/events"
    extension: "json"
    format: "json"
    create: true
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "location", label: "Lieu", widget: "string" }
      - { name: "image", label: "Photo1", widget: "image" }
      - { name: "image", label: "Photo2", widget: "image" }